### ISSUE TITLE
Color schemes for Dialog

### ISSUE THREAD

**Issue by leoj3n** [x0054/hyperjump#9]
I'm trying to load color schemes for Dialog, but am unsure how to utilize the color `.rc` files.

For example, `slackware.rc` exists in the `samples` dir of dialog source code and there are [screenshots on the dialog site](http://invisible-island.net/dialog/dialog-figures.html#list_colors).

Any idea how to get dialog to notice an `.rc` file to modify the color scheme?

**Comment by x0054** [comment]
Sorry, been a while since I logged in. Dialog looks for `.dialogrc` file in the home directory. Just move the `slackware.rc` to `~/.dialogrc` and it should work. I tested it on OSX and Ubuntu, should work on everything though.
